// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhatsAppAI.Infrastructure.Persistence;

#nullable disable

namespace WhatsAppAI.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("WhatsAppAI.Domain.Identity.Invitation", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("ConsumedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("consumed_at");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at");

                b.Property<Guid>("CreatedByUserId")
                    .HasColumnType("uuid")
                    .HasColumnName("created_by_user_id");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("character varying(300)")
                    .HasColumnName("email");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("expires_at");

                b.Property<string>("Purpose")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("purpose");

                b.Property<DateTime?>("RevokedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("revoked_at");

                b.Property<Guid?>("RevokedByUserId")
                    .HasColumnType("uuid")
                    .HasColumnName("revoked_by_user_id");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid")
                    .HasColumnName("tenant_id");

                b.Property<string>("TokenHash")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("token_hash");

                b.Property<Guid?>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0)
                    .HasColumnName("version");

                b.HasKey("Id")
                    .HasName("pk_invitations");

                b.HasIndex("ExpiresAt")
                    .HasDatabaseName("ix_invitations_expires_at");

                b.HasIndex("TokenHash")
                    .IsUnique()
                    .HasDatabaseName("ix_invitations_token_hash");

                b.HasIndex("TenantId", "Email", "Status")
                    .HasDatabaseName("ix_invitations_tenant_id_email_status");

                b.ToTable("invitations", (string)null);
            });

        modelBuilder.Entity("WhatsAppAI.Domain.Identity.Tenant", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("name");

                b.Property<DateTime?>("ReactivatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("reactivated_at");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status");

                b.Property<DateTime?>("SuspendedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("suspended_at");

                b.Property<string>("SuspensionReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("suspension_reason");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0)
                    .HasColumnName("version");

                b.HasKey("Id")
                    .HasName("pk_tenants");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("ix_tenants_name");

                b.HasIndex("Status")
                    .HasDatabaseName("ix_tenants_status");

                b.ToTable("tenants", (string)null);
            });

        modelBuilder.Entity("WhatsAppAI.Domain.Identity.TenantMembership", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at");

                b.Property<DateTime?>("DeactivatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("deactivated_at");

                b.Property<DateTime?>("ReactivatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("reactivated_at");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("role");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid")
                    .HasColumnName("tenant_id");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0)
                    .HasColumnName("version");

                b.HasKey("Id")
                    .HasName("pk_tenant_memberships");

                b.HasIndex("Status")
                    .HasDatabaseName("ix_tenant_memberships_status");

                b.HasIndex("TenantId", "UserId")
                    .IsUnique()
                    .HasDatabaseName("ix_tenant_memberships_tenant_id_user_id");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_tenant_memberships_user_id");

                b.ToTable("tenant_memberships", (string)null);
            });

        modelBuilder.Entity("WhatsAppAI.Domain.Identity.User", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime?>("ActivatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("activated_at");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at");

                b.Property<string>("DisplayName")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("display_name");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("character varying(300)")
                    .HasColumnName("email");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean")
                    .HasColumnName("is_active");

                b.Property<DateTime?>("LastLoginAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("last_login_at");

                b.Property<string>("PasswordHash")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("password_hash");

                b.Property<string>("SecurityStamp")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("security_stamp");

                b.HasKey("Id")
                    .HasName("pk_users");

                b.HasIndex("Email")
                    .IsUnique()
                    .HasDatabaseName("ix_users_email");

                b.HasIndex("SecurityStamp")
                    .HasDatabaseName("ix_users_security_stamp");

                b.ToTable("users", (string)null);
            });

        modelBuilder.Entity("WhatsAppAI.Domain.Identity.Invitation", b =>
            {
                b.HasOne("WhatsAppAI.Domain.Identity.Tenant", "Tenant")
                    .WithMany()
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_invitations_tenants_tenant_id");

                b.HasOne("WhatsAppAI.Domain.Identity.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("fk_invitations_users_user_id");

                b.Navigation("Tenant");

                b.Navigation("User");
            });

        modelBuilder.Entity("WhatsAppAI.Domain.Identity.TenantMembership", b =>
            {
                b.HasOne("WhatsAppAI.Domain.Identity.Tenant", "Tenant")
                    .WithMany("Memberships")
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_tenant_memberships_tenants_tenant_id");

                b.HasOne("WhatsAppAI.Domain.Identity.User", "User")
                    .WithMany("Memberships")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_tenant_memberships_users_user_id");

                b.Navigation("Tenant");

                b.Navigation("User");
            });

        modelBuilder.Entity("WhatsAppAI.Domain.Identity.Tenant", b =>
            {
                b.Navigation("Memberships");
            });

        modelBuilder.Entity("WhatsAppAI.Domain.Identity.User", b =>
            {
                b.Navigation("Memberships");
            });
#pragma warning restore 612, 618
    }
}
